### ISSUE TITLE
Unable to authenticate to more than one server with 2FA enabled

### ISSUE THREAD

**Issue by philipptrenz** [matomo-org/matomo-mobile-2#5429] opened 2021-11-16 13:05 UTC
Hey there, 

I have Matomo instances running, both with 2FA enabled accounts. When I try to add the second server to Matomo Mobile 2 on iOS, it results in the following error:

![IMG_4528](https://user-images.githubusercontent.com/11627598/141989906-53815f86-3cae-475a-84d0-97807f88cf30.jpg)
 
Having the first server with 2FA enabled and the second without 2FA, then it works flawlessly.

**Comment by tsteur** [comment] 2021-11-16 19:37
@philipptrenz the error message says there may be a weak password used? It doesn't look maybe like it is a 2FA issue?

**Comment by philipptrenz** [comment] 2021-11-16 20:49
Hi @tsteur, the password has more than 20 chars and is randomly generated, wouldn't consider that as weak 😉 But I also was a bit irritated by the message.

**Comment by tsteur** [comment] 2021-11-17 03:20
@philipptrenz do you get the same error when you try to log in using the regular browser? Or does it work there?

Indeed it definitely isn't weak :) 

It's bit weird as it seems. to only happen if either all characters in the password are the same, or if password length is less than 6 characters.

**Comment by philipptrenz** [comment] 2021-11-17 07:51
Hi @tsteur, sorry forgot to mention it: Yes, login using 2FA via the web interface works as expected. 

If you can give me the exact API parameters used by the app, I can do a dry API call to rule out that the error is in the API.

**Comment by philipptrenz** [comment] 2021-11-17 13:19
I took a look into the server logs, Matomo returns 200s:

```log
example.com 0 79.*.*.* - - [17/Nov/2021:14:13:15 +0100] "POST /index.php HTTP/2.0" 200 252 "-" "Appcelerator Titanium/0.0.0 ..."
example.com 0 79.*.*.* - - [17/Nov/2021:14:13:16 +0100] "POST /index.php HTTP/2.0" 200 206 "-" "Appcelerator Titanium/0.0.0 ..."
```

Kind of expected, as the error dialog says `status` is `no error`. I think we can rule out a bug in the API, the error handling of the app seems to be a bit inaccurate in this case 😉

**Comment by tsteur** [comment] 2021-11-17 19:20
I think it might be the Matomo API still returning an HTTP 200 for this.

It seems the password that Matomo Mobile is sending is too short. The check for password being weak is checked on the password in the API call, not your actual password.

Do you get to see screen where it asks you for the 2FA at all? Or do you get this error directly after entering username and password?

**Comment by philipptrenz** [comment] 2021-11-17 20:05
Ah, alright! The error dialog pops up as soon as I click the "Login" button, the 2FA screen does not show up.

**Comment by tsteur** [comment] 2021-11-17 20:22
Thanks for this. Sorry for the many questions @philipptrenz . I struggle to reproduce it so far, is there maybe any special character in your password that would help me to reproduce it? 
Do you mind letting us know the device and iOS version?

**Comment by philipptrenz** [comment] 2021-11-17 20:52
No worries, thanks for keeping up! Indeed my password contained special characters. I now changed it and can now also login on Matomo Mobile.

For reference, the password had 32 chars and contained following special characters: `&`, `^`, `@`

**Comment by tsteur** [comment] 2021-11-18 06:08
I actually just realise this is a duplicate of https://github.com/matomo-org/matomo-mobile-2/issues/5423

A workaround would be to log in using a token see https://matomo.org/faq/general/faq_114/

or to change the password.

i've tried to debug this and possibly fix it by upgrading to the latest SDK but that will be a bit of work and not expecting a fix in the next 4 weeks.

**Comment by tsteur** [comment] 2021-11-18 07:52
The API request it generates is eg 

`index.php?userLogin=test&passwordConfirmation=r&a%5Erer%40ere&description=Matomo%20Mobile%202&method=UsersManager.createAppSpecificTokenAuth&module=API&date=today&token_auth=anonymous&period=day&format=json&language=en&`

What Matomo sees as password is `r` because of the `&`.

When I change the url parameters from `encode` to `encodeUriComponent` then it results in:

`userLogin=test&passwordConfirmation=r%26a%5Erer%40ere&description=`

Which then Matomo interprets as `r&amp;a^rer@ere` as there seems a bug in Matomo. I know how to fix this one and will create an issue for this.

**Comment by philipptrenz** [comment] 2021-11-18 20:55
You guys are awesome!

**Closed** 2021-11-22 00:21 UTC
Labels: duplicate
